### PR TITLE
Make it https ready

### PR DESCRIPTION
**Pull request by vergissberlin**
It is not possible to start that application on an https domain, because of mixed content. The modern browsers block this.
Conversely, loading files from a secure server from an http website isn't a problem.

### CODE REVIEW

**Comment by schaebo** [comment]
@cla-bot check

**Comment by vergissberlin** [comment]
@schaebo Himn

**Comment by jforge** [comment]
I would suggest to rather close this PR because the commit does not solve the problem properly.
Instead of defining a schema in the urls, just remove the write and write href="// ..."

**Comment by pglombardo** [comment]
Thank you everybody for the contributions and help.  There is an entirely new websocket client in the works that will be released soon.  This new version supports SSL out of the box.

You can try this new client out now - it's part of [HiveMQ Cloud](https://www.hivemq.com/mqtt-cloud-broker/).  Getting the source prepped and onto Github is still in progress.

Screenshot 2022-11-28 at 10 19 23

Considering the above, I'll close this PR out in anticipation for the new updated client.

Thanks again to all for contributing.

**Pull request closed without merging**
